/*
 * foglio.java
 *
 * Created on 13 gennaio 2008, 14.09
 */

package com.brevevita.videonoleggio.prove;

import javax.swing.*;
import java.util.Vector;

/**
 *
 * @author  Michele
 */
public class foglio extends JPanel {
    
    /** Creates new form foglio */
    public foglio() {
       // initComponents();
    }
    
    public foglio(Vector<Object> r, Vector<Object> c) {
        rows = r;
        columns = c;
        init();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        add(jTable1, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents
    
    public void init(){
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            rows,
            columns
        ));
        add(jTable1, java.awt.BorderLayout.CENTER);

    }
 
                
    public void setColumns(Vector<Object> list){
        rows = list;
    }
    
    public void setRows(Vector<Object> list){
       columns = list;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private Vector<Object> rows,columns;
    
        public static void main(String[] args) {
        JFrame app = new JFrame("prova");
        app.setVisible(true);
        //app.add
    }
}
