/*
 * ArticoliPanel.java
 *
 * Created on 12 gennaio 2008, 20.02
 */

package com.sun.demo.addressbook;

import java.awt.event.ActionListener;

/**
 *
 * @author Michele
 */
public class ArticoloPanel extends javax.swing.JPanel {
    
    /** Creates a new instance of ArticoliPanel */
    public ArticoloPanel() {
        initComponents();
        this.articolo = new Articolo(); 
    }
    
       /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        
        lblCod = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        lblTitolo = new javax.swing.JLabel();
        txtTitolo = new javax.swing.JTextField(25);
        lblRegista = new javax.swing.JLabel();
        txtRegista = new javax.swing.JTextField();
        lblAttori = new javax.swing.JLabel();
        txtAttori = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtPostalCode = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        lblPostalCode = new javax.swing.JLabel();
        lblSupporto = new javax.swing.JLabel();
        txtSupporto = new javax.swing.JTextField();
        lblPrezzo = new javax.swing.JLabel();
        txtPrezzo = new javax.swing.JTextField();
        lblNazione = new javax.swing.JLabel();
        txtNazione = new javax.swing.JTextField();
        lblInfo2 = new javax.swing.JLabel();
        txtInfo2 = new javax.swing.JTextField();
        lblDescrizione = new javax.swing.JLabel();
        txtDescrizione = new javax.swing.JTextField();
        lblAnno = new javax.swing.JLabel();
        txtAnno = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        lblTitolo.setText("Titolo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblTitolo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtTitolo, gridBagConstraints);

        lblRegista.setText("Regista");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblRegista, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtRegista, gridBagConstraints);

        lblAttori.setText("Attori");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblAttori, gridBagConstraints);

        txtAttori.setMinimumSize(new java.awt.Dimension(100, 21));
        txtAttori.setPreferredSize(new java.awt.Dimension(100, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtAttori, gridBagConstraints);

        /*txtState.setMinimumSize(new java.awt.Dimension(30, 21));
        txtState.setPreferredSize(new java.awt.Dimension(30, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtState, gridBagConstraints);

        txtPostalCode.setMinimumSize(new java.awt.Dimension(80, 21));
        txtPostalCode.setPreferredSize(new java.awt.Dimension(80, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtPostalCode, gridBagConstraints);

        lblState.setText("State");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblState, gridBagConstraints);

        lblPostalCode.setText("ZIP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblPostalCode, gridBagConstraints);*/

        lblSupporto.setText("Supporto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblSupporto, gridBagConstraints);

        txtSupporto.setMinimumSize(new java.awt.Dimension(100, 21));
        txtSupporto.setPreferredSize(new java.awt.Dimension(100, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtSupporto, gridBagConstraints);

        lblPrezzo.setText("Prezzo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblPrezzo, gridBagConstraints);

        txtPrezzo.setMinimumSize(new java.awt.Dimension(80, 21));
        txtPrezzo.setPreferredSize(new java.awt.Dimension(80, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtPrezzo, gridBagConstraints);

        lblNazione.setText("Nazione");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblNazione, gridBagConstraints);

        txtNazione.setMinimumSize(new java.awt.Dimension(80, 21));
        txtNazione.setPreferredSize(new java.awt.Dimension(80, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtNazione, gridBagConstraints);

        lblDescrizione.setText("Descrizione");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblDescrizione, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtDescrizione, gridBagConstraints);

        lblAnno.setText("Anno");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblAnno, gridBagConstraints);
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtAnno, gridBagConstraints);
        
        lblCod.setText("Codice");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblCod, gridBagConstraints);
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;

        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtCod, gridBagConstraints);

    }// </editor-fold>     
    
    void setCodice(String cod) {
        articolo.setCodice(cod.toUpperCase());
        txtCod.setText(cod.toUpperCase());
    }
    
    String getCodice() {
        String cod = txtCod.getText().toUpperCase();
        articolo.setCodice(cod);
        return cod;
    }
    
    void setTitolo(String ss) {
        articolo.setTitolo(ss.toUpperCase());
        txtTitolo.setText(ss.toUpperCase());
    }
    
    String getTitolo() {
        String t = txtTitolo.getText().toUpperCase();
         if(t.length()>59) 
            t = t.substring(0,59);
        articolo.setTitolo(t);
        return t;
    }
    
    void setRegista(String ss) {
        articolo.setRegista(ss);
        txtRegista.setText(ss);
    }
    
    String getRegista() {
        String t = txtRegista.getText();
        articolo.setRegista(t);
        return t;
    }
    
    void setAttori(String ss) {
        articolo.setAttori(ss);
        txtAttori.setText(ss);
    }
    
    String getAttori() {
        String t = txtAttori.getText();
        articolo.setAttori(t);
        return t;
    }
    
    void setAnno(String ss) {
        articolo.setAnno(ss);
        txtAnno.setText(ss);
    }
    
    String getAnno() {
        String a = txtAnno.getText();
        if(a.length()>4) 
            a = a.substring(0,4);
        articolo.setAnno(a);
        return a;
    }
    
    void setDescrizione(String ss) {
        articolo.setDescrizione(ss);
        txtDescrizione.setText(ss);
    }
    
    String getDescrizione() {
        String t = txtDescrizione.getText();
        articolo.setDescrizione(t);
        return t;
    }
    
    void setPrezzo(String ss) {
        articolo.setPrezzo(ss);
        txtPrezzo.setText(ss);
    }
    
    String getPrezzo() {
        String t = txtPrezzo.getText();
        articolo.setPrezzo(t);
        return t;
    }
    
    void setSupporto(String ss) {
        articolo.setSupporto(ss.toUpperCase());
        txtSupporto.setText(ss.toUpperCase());
    }
    
    String getSupporto() {
        String t = txtSupporto.getText().toUpperCase();
        articolo.setSupporto(t);
        return t;
    }
    
    void setInfo1(String ss) {
        articolo.setInfo1(ss.toUpperCase());
        txtNazione.setText(ss.toUpperCase());
    }
    
    String getInfo1() {
        String t = txtNazione.getText().toUpperCase();
        articolo.setInfo1(t);
        return t;
    }
    
    void setInfo2(String ss) {
        articolo.setInfo2(ss);
        txtInfo2.setText(ss);
    }
    
    String getInfo2() {
        String t = txtInfo2.getText();
        articolo.setInfo2(t);
        return t;
    }
    
    void setId(int id) {
        articolo.setId(id);
        this.id = id;
    }
    
    public int getId() {
        int id = this.id;
        articolo.setId(id);
        return id;
    }
    
    
    public void setArticolo(Articolo articolo) {
        if (articolo != null) {
            setCodice(articolo.getCodice());
            setTitolo(articolo.getTitolo());
            setRegista(articolo.getRegista());
            setAttori(articolo.getAttori());
            setAnno(articolo.getAnno());
            setDescrizione(articolo.getDescrizione());
            setPrezzo(articolo.getPrezzo());
            setSupporto(articolo.getSupporto());
            setInfo1(articolo.getInfo1());
            setInfo2(articolo.getInfo2());
            setId(articolo.getId());

        }
    }
        
    
    public Articolo getArticolo() {
        getCodice();
        getTitolo();
        getRegista();
        getAttori();
        getAnno();
        getDescrizione();
        getPrezzo();
        getSupporto();
        getInfo1();
        getInfo2();
        getId();     

        return articolo;
    }
    
    
    
    public void clear() {
        txtCod.setText(null);
        txtTitolo.setText(null);
        txtRegista.setText(null);
        txtAttori.setText(null);
        txtAnno.setText(null);
        txtDescrizione.setText(null);
        txtPrezzo.setText(null);
        txtSupporto.setText(null);
        txtNazione.setText(null);
        txtInfo2.setText(null);
        
        txtState.setText(null);
        txtPostalCode.setText(null);

        id = -1;
        articolo = new Articolo();
    }
    
    public void setEditable(boolean bEditable) {
        txtCod.setEditable(bEditable);
        txtTitolo.setEditable(bEditable);
        txtRegista.setEditable(bEditable);
        txtAttori.setEditable(bEditable);
        txtAnno.setEditable(bEditable);
        txtDescrizione.setEditable(bEditable);
        txtPrezzo.setEditable(bEditable);
        txtSupporto.setEditable(bEditable);
        txtNazione.setEditable(bEditable);
        txtInfo2.setEditable(bEditable);
        

        txtDescrizione.setEditable(bEditable);
        txtPrezzo.setEditable(bEditable);
        isEditable = bEditable;
    }
    
    public boolean isEditable() {
        return isEditable;
    }
    
        // Variables declaration - do not modify      
    private javax.swing.JLabel lblCod;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JLabel lblRegista;
    private javax.swing.JLabel lblAttori;
    private javax.swing.JLabel lblAnno;
    private javax.swing.JLabel lblDescrizione;
    private javax.swing.JLabel lblPrezzo;
    private javax.swing.JLabel lblSupporto;
    private javax.swing.JLabel lblNazione;
    private javax.swing.JLabel lblInfo2;
    
    private javax.swing.JLabel lblPostalCode;
    private javax.swing.JLabel lblState;
    
    
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtTitolo;
    private javax.swing.JTextField txtRegista;
    private javax.swing.JTextField txtAttori;
    private javax.swing.JTextField txtAnno;
    private javax.swing.JTextField txtDescrizione;
    private javax.swing.JTextField txtPrezzo;
    private javax.swing.JTextField txtSupporto;
    private javax.swing.JTextField txtNazione;
    private javax.swing.JTextField txtInfo2;
    

    private javax.swing.JTextField txtPostalCode;
    private javax.swing.JTextField txtState;
    
    int id;
    boolean isEditable;
    Articolo articolo;
}
