/*
 * ClientiFrame.java
 *
 * Created on 5 gennaio 2008, 15.27
 *
 * To change this template, choose Tools | Options and locate the template under
 * the Source Creation and Management node. Right-click the template and choose
 * Open. You can then make changes to the template in the Source Editor.
 */

package com.sun.demo.addressbook;


import com.brevevita.videonoleggio.db.bvdb;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.net.URL;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author  Michele Piunti
 */
public class ClientiFrame 
        extends javax.swing.JFrame 
        implements ActionListener, ListSelectionListener {
    
    /** Creates new form AddressFrame */
    public ClientiFrame() {
        initComponents();
        loadFrameIcon();
        windowAdapter = new WindowCloser();
        this.addWindowListener(windowAdapter);
        db = new bvdb();
        db.connect();
        addressActionPanel.addActionListener(this);
        BrevevitaPanel.setEditable(false);
        List<ListEntry> entries = db.getListClienti();
        addressListPanel.addListEntries(entries);
        addressListPanel.addListSelectionListener(this);
    }
    
   
    /**
     * Load our own "address book" icon into our frame window.
     */
    private void loadFrameIcon() {
        URL imgUrl = null;
        ImageIcon imgIcon = null;
        
        imgUrl = ClientiFrame.class.getResource("resource/addressbook32.gif");
        imgIcon = new ImageIcon(imgUrl);
        Image img = imgIcon.getImage();
        this.setIconImage(img);
        
    }    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">                          
    private void initComponents() {
        addressActionPanel = new com.sun.demo.addressbook.AddressActionPanel();
        BrevevitaPanel = new com.sun.demo.addressbook.ClientePanel();
        addressListPanel = new com.sun.demo.addressbook.AddressListPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Address Book Demo");
        getContentPane().add(addressActionPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(BrevevitaPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(addressListPanel, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>                        


    
    private void cancelCliente() {
        BrevevitaPanel.clear();
        BrevevitaPanel.setEditable(false);
        ListEntry entry = addressListPanel.getSelectedListEntry();
        if (entry != null) {
            int id = entry.getId();
            Cliente cliente = db.getCliente(id);
            BrevevitaPanel.setCliente(cliente);
        }
        
        
    }
    
    private void newCliente(){
        BrevevitaPanel.clear();
        BrevevitaPanel.setEditable(true);
        
    }
    
    private void deleteCliente() {
        int id = BrevevitaPanel.getId();
        if (id != -1) {
            db.deleteCliente(id);
            int selectedIndex = addressListPanel.deleteSelectedEntry();
            if (selectedIndex >= 0) {
                selectedIndex = addressListPanel.setSelectedIndex(selectedIndex);
                ListEntry entry = addressListPanel.getSelectedListEntry();
                if (entry != null) {
                    id = entry.getId();
                    Cliente cliente = db.getCliente(id);
                    BrevevitaPanel.setCliente(cliente);
                } else {
                    BrevevitaPanel.clear();
                }
            }
        } else {
            BrevevitaPanel.clear();
        }
        BrevevitaPanel.setEditable(false);
        
        
        
    }
    
    private void editCliente() {
        int selected = addressListPanel.getSelectedIndex();
        if (selected >=0) {
            BrevevitaPanel.setEditable(true);
        }
        
    }
    
    private void saveCliente() {
        if (BrevevitaPanel.isEditable()) {
            Cliente cliente = BrevevitaPanel.getCliente();
            int id = cliente.getId();
                String lname = cliente.getLastName();
                String fname = cliente.getFirstName();
                String mname = cliente.getMiddleName();
            if (id == -1) {
                id = db.saveCliente(cliente);
                cliente.setId(id);

                ListEntry entry = new ListEntry(lname, fname, mname, id);
                addressListPanel.addListEntry(entry);

            } else {
                db.editCliente(cliente);
                ListEntry entry = addressListPanel.getSelectedListEntry();
                entry.setFirstName(fname);
                entry.setMiddleName(mname);
                entry.setLastName(lname);
                addressListPanel.repaint();
            }
            BrevevitaPanel.setEditable(false);
        }
    }
    
    
    public void actionPerformed(ActionEvent e) {
        String actionCommand = e.getActionCommand();
        System.out.println("ActionEvent: " + actionCommand);
        if (actionCommand.equalsIgnoreCase("CANCEL_ADDRESS")) {
            cancelCliente();
        } else if (actionCommand.equalsIgnoreCase("NEW_CLIENTE")) {
            newCliente();
        } else if (actionCommand.equalsIgnoreCase("CANCEL_CLIENTE")) {
            deleteCliente();
        } else if (actionCommand.equalsIgnoreCase("EDIT_CLIENTE")) {
            editCliente();
        } else if (actionCommand.equalsIgnoreCase("SAVE_CLIENTE")) {
            saveCliente();
        }
    }

    public static void main(String[] args) {
        ClientiFrame app = new ClientiFrame();
        app.setVisible(true);
    }

    public void valueChanged(ListSelectionEvent e) {
        if (e.getValueIsAdjusting()) {
            return;
        }
        JList entryList = (JList) e.getSource();
        selectedEntry = entryList.getSelectedIndex();
        ListEntry entry = (ListEntry)entryList.getSelectedValue();
        if (entry != null) {
            int id = entry.getId();
            Cliente cliente = db.getCliente(id);
            BrevevitaPanel.setCliente(cliente);
        } else {
            BrevevitaPanel.clear();
        }
    }
    
    
    // Variables declaration - do not modify                     
    private com.sun.demo.addressbook.AddressActionPanel addressActionPanel;
    private com.sun.demo.addressbook.AddressListPanel addressListPanel;
    private com.sun.demo.addressbook.ClientePanel BrevevitaPanel;
    // End of variables declaration                   
    
    private int selectedEntry = -1;
    private bvdb db;
    private WindowAdapter windowAdapter;
    
    class WindowCloser extends WindowAdapter {
        public void windowClosing(WindowEvent e) {
            db.disconnect();
        }
    
    }
}
